"""CLI interface for ScreenParse — parse screenshots and accessibility data."""

from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

import click

from screenparse import __version__
from screenparse.element import ParseResult
from screenparse.parser import ScreenParser


def _setup_logging(quiet: bool = False, verbose: bool = False) -> None:
    """Configure logging based on CLI flags."""
    if quiet:
        level = logging.WARNING
    elif verbose:
        level = logging.DEBUG
    else:
        level = logging.INFO
    
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )


SAMPLE_CONFIG = """# ScreenParse Configuration
# Generated by screenparse sample-config

image:
  # Minimum area (in pixels) for an element to be detected
  min_element_area: 100
  # Color threshold for solid region detection (lower = more strict)
  color_threshold: 0.15
  # Maximum number of elements to detect
  max_elements: 200

accessibility:
  # Include hidden elements in the parse result
  include_hidden: false

output:
  # Output format: json or yaml
  format: json
  # Pretty-print the output
  pretty_print: true
"""


@click.group(invoke_without_command=True)
@click.version_option(version=__version__, prog_name="screenparse")
@click.option("--quiet", "-q", is_flag=True, help="Suppress non-essential output.")
@click.option("--verbose", "-v", is_flag=True, help="Enable verbose/debug output.")
@click.pass_context
def main(ctx: click.Context, quiet: bool, verbose: bool) -> None:
    """ScreenParse — UI element parser for AI phone agents.
    
    Analyze screenshots and accessibility dumps to extract structured
    UI element information for automation and AI agents.
    """
    _setup_logging(quiet=quiet, verbose=verbose)
    
    if ctx.invoked_subcommand is None and ctx.obj is not None:
        click.echo(main.get_help(ctx))


@main.command()
@click.option(
    "--image", "-i",
    "image_path",
    type=click.Path(exists=True, readable=True, path_type=Path),
    help="Path to screenshot image file.",
)
@click.option(
    "--accessibility", "-a",
    "accessibility_path",
    type=click.Path(exists=True, readable=True, path_type=Path),
    help="Path to accessibility dump file.",
)
@click.option(
    "--output", "-o",
    type=click.Path(path_type=Path),
    help="Output file path. Defaults to stdout.",
)
@click.option(
    "--types", "-t",
    type=str,
    help="Comma-separated element types to filter (e.g., button,input,text).",
)
@click.option(
    "--stats", is_flag=True,
    help="Show summary statistics after output.",
)
@click.option(
    "--verbose", is_flag=True,
    help="Verbose parsing output.",
)
@click.pass_context
def parse(
    ctx: click.Context,
    image_path: Path | None,
    accessibility_path: Path | None,
    output: Path | None,
    types: str | None,
    stats: bool,
    verbose: bool,
) -> None:
    """Parse a screenshot image or accessibility dump.
    
    Analyzes the input file and extracts UI elements with their
    positions, types, and text content.
    """
    _setup_logging(quiet=ctx.obj.get("quiet", False), verbose=verbose or ctx.obj.get("verbose", False))
    
    parser = ScreenParser()
    
    try:
        result = parser.parse_and_output(
            image_path=image_path,
            accessibility_path=accessibility_path,
            output_path=str(output) if output else None,
            stats=stats,
            verbose=verbose,
        )
    except FileNotFoundError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)
    except ValueError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)
    
    # Print stats if requested
    if stats:
        click.echo("\n--- Statistics ---")
        click.echo(f"Total elements: {result.element_count}")
        click.echo(f"Top-level elements: {len(result.elements)}")
        click.echo(f"Parse time: {result.parse_time_ms:.2f} ms")
        if result.image_width > 0:
            click.echo(f"Image: {result.image_width}x{result.image_height}")
        if result.type_counts:
            click.echo("Element types:")
            for etype, count in sorted(result.type_counts.items()):
                click.echo(f"  {etype}: {count}")
        if result.warnings:
            click.echo("Warnings:")
            for warning in result.warnings:
                click.echo(f"  - {warning}")
    
    # Filter by type if requested
    if types:
        type_filter = set(t.strip().lower() for t in types.split(","))
        filtered_elements = [
            e for e in result.elements
            if e.element_type.value in type_filter
        ]
        if output:
            filtered_data = {
                "source_type": result.source_type,
                "source_path": result.source_path,
                "element_count": len(filtered_elements),
                "elements": [e.to_dict() for e in filtered_elements],
            }
            out = Path(output)
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(json.dumps(filtered_data, indent=2), encoding="utf-8")
            click.echo(f"\nFiltered to {len(filtered_elements)} elements, written to {output}")


@main.command()
@click.option(
    "--image", "-i",
    "image_path",
    type=click.Path(exists=True, readable=True, path_type=Path),
    help="Path to screenshot image file.",
)
@click.option(
    "--accessibility", "-a",
    "accessibility_path",
    type=click.Path(exists=True, readable=True, path_type=Path),
    help="Path to accessibility dump file.",
)
@click.option(
    "--verbose", is_flag=True,
    help="Verbose output.",
)
@click.pass_context
def analyze(
    ctx: click.Context,
    image_path: Path | None,
    accessibility_path: Path | None,
    verbose: bool,
) -> None:
    """Analyze screen layout and element distribution.
    
    Provides a high-level summary of the UI structure without
    extracting individual element details.
    """
    _setup_logging(quiet=ctx.obj.get("quiet", False), verbose=verbose or ctx.obj.get("verbose", False))
    
    parser = ScreenParser()
    
    try:
        result = parser.parse(
            image_path=image_path,
            accessibility_path=accessibility_path,
        )
    except FileNotFoundError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)
    except ValueError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)
    
    click.echo("=" * 60)
    click.echo("Screen Analysis Report")
    click.echo("=" * 60)
    click.echo(f"\nSource: {result.source_path}")
    click.echo(f"Source type: {result.source_type}")
    click.echo(f"Parse time: {result.parse_time_ms:.2f} ms")
    
    if result.image_width > 0:
        click.echo(f"Dimensions: {result.image_width}x{result.image_height}")
    
    click.echo(f"\nTotal elements: {result.element_count}")
    click.echo(f"Top-level elements: {len(result.elements)}")
    
    if result.type_counts:
        click.echo("\nElement Distribution:")
        total = sum(result.type_counts.values())
        for etype, count in sorted(result.type_counts.items(), key=lambda x: -x[1]):
            pct = count / total * 100 if total > 0 else 0
            click.echo(f"  {etype:15s}: {count:4d} ({pct:5.1f}%)")
    
    if result.warnings:
        click.echo(f"\nWarnings ({len(result.warnings)}):")
        for warning in result.warnings:
            click.echo(f"  ⚠ {warning}")
    
    # Element density analysis
    if result.image_width > 0 and result.image_height > 0:
        area = result.image_width * result.image_height
        elements_per_1000 = len(result.elements) / (area / 1000)
        click.echo(f"\nElement density: {elements_per_1000:.2f} per 1000px²")
    
    click.echo("=" * 60)


@main.command()
def info() -> None:
    """Show project information and supported formats."""
    from screenparse import __version__
    
    click.echo("=" * 60)
    click.echo("ScreenParse")
    click.echo(f"Version: {__version__}")
    click.echo("=" * 60)
    
    click.echo("\nSupported Image Formats:")
    for fmt in ["PNG", "JPG", "JPEG", "BMP", "WebP", "GIF"]:
        click.echo(f"  • {fmt}")
    
    click.echo("\nSupported Accessibility Formats:")
    click.echo("  • Android XML (uiautomator dump)")
    click.echo("  • iOS plist (basic)")
    
    click.echo("\nOutput Formats:")
    click.echo("  • JSON (default)")
    click.echo("  • YAML")
    
    click.echo("\nElement Types Detected:")
    for etype in ["button", "text", "image", "input", "icon", "container", "checkbox", "radio", "list", "link", "unknown"]:
        click.echo(f"  • {etype}")
    
    click.echo("\n" + "=" * 60)


@main.command()
def sample_config() -> None:
    """Generate a sample configuration file."""
    click.echo(SAMPLE_CONFIG.strip())


if __name__ == "__main__":
    main()
